// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuqa6M01aiWxh8-y6spgdPRGY6x47g3c8',
    appId: '1:314173324910:web:84e81f108f9b6ba4c2707f',
    messagingSenderId: '314173324910',
    projectId: 'store-b179f',
    authDomain: 'store-b179f.firebaseapp.com',
    storageBucket: 'store-b179f.firebasestorage.app',
    measurementId: 'G-6J1R4GMNYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDBCQnMs_e9D1LLK3UwlMzlqKmEk_KWcE',
    appId: '1:314173324910:android:6b1d3ffa7cedaefac2707f',
    messagingSenderId: '314173324910',
    projectId: 'store-b179f',
    storageBucket: 'store-b179f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_v0OtEaobSkJdLs6oAtJcdBfRspKaPdk',
    appId: '1:314173324910:ios:9d1bc85d57dcb0acc2707f',
    messagingSenderId: '314173324910',
    projectId: 'store-b179f',
    storageBucket: 'store-b179f.firebasestorage.app',
    iosBundleId: 'com.example.storeManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_v0OtEaobSkJdLs6oAtJcdBfRspKaPdk',
    appId: '1:314173324910:ios:9d1bc85d57dcb0acc2707f',
    messagingSenderId: '314173324910',
    projectId: 'store-b179f',
    storageBucket: 'store-b179f.firebasestorage.app',
    iosBundleId: 'com.example.storeManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuqa6M01aiWxh8-y6spgdPRGY6x47g3c8',
    appId: '1:314173324910:web:7eaed77fc0f1b9d9c2707f',
    messagingSenderId: '314173324910',
    projectId: 'store-b179f',
    authDomain: 'store-b179f.firebaseapp.com',
    storageBucket: 'store-b179f.firebasestorage.app',
    measurementId: 'G-43SJY96HGK',
  );
}
